In [1]:
from google.colab import drive
import os
import re

# Muntar Google Drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
from pathlib import Path
import re
import pandas as pd

FOLDER = Path("/content/TFG/DLFuzz/Resultats_imagenet")

rows = []

for txt in FOLDER.glob('*.txt'):
    with open(txt, 'r', encoding='utf-8') as fh:
        for line in reversed(fh.readlines()):
            if line.strip().startswith('total_time'):
                total_time = float(line.split('=')[1])
                break

    m = re.search(r'(\d{2})(?=\.txt$)', txt.name)
    if m is None:
        raise ValueError(f"No s’han trobat dos dígits al final del nom: {txt.name}")

    digits = m.group(1)
    model     = int(digits[0])
    strategy  = int(digits[1]) + 1

    rows.append({'Model': model, 'Strategy': strategy, 'Total_time': total_time})


df = pd.DataFrame(rows)
table = (
    df
    .pivot(index='Model', columns='Strategy', values='Total_time')
    .sort_index()
    .sort_index(axis=1)
)


display(table)

Strategy           1           2           3           4
Model
1         172.068238  251.152249  201.501410  158.939035
2         216.049415  279.540196  200.713842  180.990770
3         805.689138  805.369726  800.486645  778.279226

In [ ]:
from pathlib import Path
import re
import pandas as pd

FOLDER = Path("/content/TFG/DLFuzz/GTSRB/Resultats_DLFuzz_GTSRB_2imgs_per_senyal")

rows = []

for txt in FOLDER.glob('*.txt'):
    with open(txt, 'r', encoding='utf-8') as fh:
        for line in reversed(fh.readlines()):
            if line.strip().startswith('total_time'):
                total_time = float(line.split('=')[1])
                break

    m = re.search(r'(\d{2})(?=\.txt$)', txt.name)
    if m is None:
        raise ValueError(f"No s’han trobat dos dígits al final del nom: {txt.name}")

    digits = m.group(1)
    model     = int(digits[0])
    strategy  = int(digits[1]) + 1

    rows.append({'Model': model, 'Strategy': strategy, 'Total_time': total_time})


df = pd.DataFrame(rows)
table = (
    df
    .pivot(index='Model', columns='Strategy', values='Total_time')
    .sort_index()
    .sort_index(axis=1)
)


display(table)

Strategy           1           2           3           4
Model
1         526.025235  525.689445  542.069978  438.777734
2         472.322118  463.028570  466.420414  359.099815
3         505.842398  499.896921  500.202975  392.416902